# Generated by Django 5.1.7 on 2025-04-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
