# Generated by Django 5.1.7 on 2025-04-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlisting_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
