# Generated by Django 5.1.7 on 2025-04-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productlisting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='uid',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
