# Generated by Django 5.1.7 on 2025-04-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productlisting_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='uid',
            field=models.CharField(editable=False, max_length=22, unique=True),
        ),
    ]
